@startuml
'https://plantuml.com/sequence-diagram

participant Main
create "l:Labyrinthe" as laby
Main -> laby : new
create "p:Perso" as perso
Main -> perso : new
create "d:Démon" as demon
Main -> demon : new
Main -> perso : attaquer(demon)
activate perso
perso -> demon : setPV(-1)
activate demon
demon --> perso : void
deactivate demon
perso --> Main : void
deactivate perso
@enduml