@startuml
'https://plantuml.com/sequence-diagram

participant MainLaby
participant "m:MoteurJeu" as m
participant "appli:Application" as appli
MainLaby -> m : launch(jeuLaby : LabyJeu, LabyImage : LabyImage)
activate m
m -> appli : launch()
activate appli
appli -> m : start(primaryStage : Stage)
activate m
m --> appli : void
deactivate m
appli --> m : void
deactivate appli
m --> MainLaby : void
deactivate m

@enduml