@startuml

participant Main
participant "labyImage:LabyImage" as labyImage
participant "laby:Labyrinthe" as labyrinthe
participant "monster:Monster" as monster
Main -> labyImage : dessinerJeu()
activate labyImage
labyImage -> labyrinthe : getMur()
activate labyrinthe
labyImage <-- labyrinthe : mur
deactivate labyrinthe
labyImage -> labyrinthe : getMonstre()
activate labyrinthe
labyrinthe -> monster : etrePresent()
activate monster
alt monstre present
    labyrinthe <-- monster : true
else monstre absent
    labyrinthe <-- monster : false
end
deactivate monster
labyImage <-- labyrinthe : monstre
deactivate labyrinthe

@enduml