@startuml

participant Main
participant "labyImage:LabyImage" as labyImage
participant "laby:Labyrinthe" as labyrinthe
participant "d:Demon" as demon
Main -> labyImage : dessinerJeu()
activate labyImage
labyImage -> labyrinthe : getMur()
activate labyrinthe
labyImage <-- labyrinthe : mur
deactivate labyrinthe
labyImage -> labyrinthe : getMonstre()
activate labyrinthe
labyrinthe -> demon : etrePresent()
activate demon
alt demon present
    labyrinthe <-- demon : true
else demon absent
    labyrinthe <-- demon : false
end
deactivate demon
labyImage <-- labyrinthe : demon
deactivate labyrinthe

@enduml