@startuml
'https://plantuml.com/sequence-diagram

participant Main
participant "lj:LabyJeu" as lj
participant "l:Labyrinthe" as l
participant "d:Demon" as d

create lj
Main -> lj : new
Main -> lj : update(double secondes, Clavier clavier)
activate lj
lj -> l : deplacer(d, HAUT)
activate l
l -> d : seDeplacer(dx:int,dy:int)
activate d
d --> l : void
deactivate d
l --> lj : void
deactivate l
lj --> Main : void
deactivate lj


@enduml
