@startuml
'https://plantuml.com/sequence-diagram

participant Main
create "l:Labyrinthe" as l
Main -> l : new
create "p:Perso" as p
Main -> p : new
Main -> l : deplacer(p, HAUT)
activate l
l -> p : seDeplacer(dx:int, dy:int)
activate p
p --> l : void
deactivate p
l --> Main : void
deactivate l


@enduml
