@startuml
'https://plantuml.com/sequence-diagram

participant Main
participant "l:LabyDessin" as laby
participant "lab:Labyrinthe" as lab
participant "d:Demon" as demon
create laby
Main -> laby : new
Main -> laby : dessinerJeu(Jeu jeu, Canvas canvas)
activate laby
laby -> lab : getMonstre()
activate lab
lab -> demon : get(i)
activate demon
demon --> lab : void
deactivate demon
lab --> laby : void
deactivate lab
laby --> Main : void
deactivate laby


@enduml
