@startuml
'https://plantuml.com/sequence-diagram

participant Main
participant "l:Labyrinthe" as labyrinthe
participant "d:Demon" as demon
create labyrinthe
Main -> labyrinthe : new
create demon
labyrinthe -> demon : new

@enduml
