@startuml
'https://plantuml.com/sequence-diagram

participant Main
create "d:Démon" as demon
Main -> demon : new
create "p:Perso" as perso
Main -> perso
Main -> demon : attaquer(p)
activate demon
demon -> perso : setPV(-1)
activate perso
perso --> demon : void
deactivate perso
demon --> Main : void
deactivate demon

@enduml