@startuml
'https://plantuml.com/sequence-diagram

participant Main
create "m:Monstre" as monstre
Main -> monstre : new
create "p:Perso" as perso
Main -> perso
Main -> monstre : attaquer(p)
activate monstre
monstre -> perso : setPV(-1)
activate perso
perso --> monstre : void
deactivate perso
monstre --> Main : void
deactivate monstre

@enduml